### ISSUE TITLE
Add support for new attributes in content objects

### ISSUE THREAD

**Issue by dunkelstern** [anfema/ion-client-android#173]
Container Contents:

- new Attribute `subtype` can be one of
  - `generic`: no content definition, no `index`
  - `list`: all outlets of same type and named `<container_name>_item`, items contain `index` attribute
  - `structblock`: all outlet names are unique, no `index`
  - `streamblock`: outlets are not unique but contain `index` attributes

All Content types:

- Optional contains `index` attribute to mark item as part of a list

**Comment by p-fischer** [comment]
additional notes:

ION client:
- optional: Remove field `position` in `content`

on app level:
- Remove `_0` suffix in `outlet` strings. If we (temporarily) use a "startsWith" check instead of an equals check. The code would work with both the old and the new API.
